import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { ReactQueryProvider } from './ReactQueryProvider'

const montSerrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MKS FrontEnd Challenge',
  description: 'Generated by Guilherme Augusto Garcia Bernardes dos Santos',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={montSerrat.className}>{children}</body>
      </html>
    </ReactQueryProvider>
  )
}
